# Show the username
[username]
show_always = true
format = "ğŸ‘¾ [$user](bold blue) "

# Show the directory with a folder emoji ğŸ“
[directory]
truncation_length = 3
format = "ğŸ‘¾ [$path](bold purple) "
home_symbol = "ğŸ  "

# Show PHP version ğŸ˜
[php]
format = "ğŸ˜ [$version](bold magenta) "

# Show Node.js version ğŸŒ³
[nodejs]
format = "ğŸŒ³ [$version](bold green) "

# Show Python version ğŸ
[python]
format = "ğŸ [$version](bold blue) "

[vagrant]
disabled = true

[git_status]
disabled = true

[aws]
disabled = true

# Show a rocket âš¡ as the prompt symbol
[character]
success_symbol = "[âš¡ï¸](bold yellow) "
error_symbol = "[âŒ](bold red) "
